name: Deploy to AWS

on:
	push:
		branches: [main]

jobs:
	deploy:
		runs-on: ubuntu-latest
		steps:
			- uses: actions/checkout@v3
			- name: Deploy Application
				run: echo "Deploying Remote Staffing System to AWS"




				name: Deploy to AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: echo "Deploying to AWS ECS"

